name: API Tests

on:
  push:
    branches: [ main, master, cinema ]
  pull_request:
    branches: [ main, master, cinema ]
  workflow_dispatch:

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose --version
      
      - name: Start services with Docker Compose
        run: |
          docker compose up -d
          
          # Wait for services to be ready
          echo "Waiting for services to be ready..."
          sleep 120
      
      - name: Install Newman and dependencies
        working-directory: tests/postman
        run: npm install
      
      - name: Run API tests
        working-directory: tests/postman
        run: |

          # Build the Docker image
          docker build -t cinemaabyss-api-tests .     
          # Run the tests in Docker
          docker run --network=cinemaabyss-network -v "$(pwd)/reports:/app/reports" cinemaabyss-api-tests       
      
      - name: Stop services
        if: always()
        run: docker compose down